version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: .database.env
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  gateway:
    container_name: gateway
    image: devopsfaith/krakend:latest
    volumes:
      - type: bind
        source: ./krakend/config.json
        target: /etc/krakend/config.json
        read_only: true
    ports:
      - 8080:8080
      - 8091:8091
    command: [ "run", "-c", "/etc/krakend/config.json" ]
    depends_on:
    - face_api
    - static_data
  static_data:
    image: jaxgeller/lwan
    container_name: static_data
    volumes:
      - type: bind
        source: ./jwk/symmetric.json
        target: /lwan/wwwroot/jwk/symmetric.json
        read_only: true
    ports:
      - "8000:8080"
  seed:
    build:
      context: app
      dockerfile: seed.dockerfile
    container_name: seed
    command: python seed.py
    volumes:
      - type: bind
        source: ./app/.env.yaml
        target: /opt/app/.env.yaml
        read_only: true
    depends_on:
      - postgres
  face_api:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: face_api
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./app/.log-config.ini
        target: /opt/app/.log-config.ini
        read_only: true
      - type: bind
        source: ./app/.env.yaml
        target: /opt/app/.env.yaml
        read_only: true
    command: python main.py
    depends_on:
      - postgres
      - seed
    networks:
      - faceapinet
      - default
networks:
  faceapinet:
    name: faceapinet